import './styl/style.styl';
import './common.blocks/loader/js/loader.js';
import './common.blocks/pin/js/pin.js'
import './js/speakers.js';
import './common.blocks/social-icon/js/social-icon.js'
import './common.blocks/button/js/button.js';
import './common.blocks/percentage-chart/js/percentage-chart.js'
import './common.blocks/donut-chart/js/donut-chart.js'
import './common.blocks/chart-section/js/chart-section.js'
import './common.blocks/slider/js/slider.js'
import './common.blocks/email-form/js/email-form.js'
import './common.blocks/form-section/js/form-section.js'
import './common.blocks/search-box/js/search-box.js'
import './common.blocks/drop-down/js/drop-down.js'
import './common.blocks/map-section/js/map-section.js'
import './common.blocks/calendar/js/calendar.js'
import './common.blocks/calendar-section/js/calendar-section.js'
import './common.blocks/online-help/js/online-help.js'